### ISSUE TITLE
salt_water loading message error

### ISSUE THREAD

**Issue by Chronakai** [chaosvolt/MST_Extra_Mod#12]
DEBUG    : loop in comestible recipes detected: salt_water -> water_clean -> salt_water.  Such loops can be broken by either removing or altering recipes or marking one of the items involved with the NUTRIENT_OVERRIDE flag

 FUNCTION : void recipe_dictionary::find_items_on_loops()
 FILE     : src/recipe_dictionary.cpp
 LINE     : 405

See: [https://github.com/CleverRaven/Cataclysm-DDA/issues/36932](url) , finally narrowed it down to MST Extra.

**Comment by chaosvolt** [comment]
Update MST Extra, I had to obsolete that recipe and re-implement it via a different method, it was fixed 2 weeks ago by this: https://github.com/chaosvolt/MST_Extra_Mod/commit/c2584e9661fc163aceaebda719cb6c52f418fb36
