### ISSUE TITLE
Furnitures and Terrain Overrides

### ISSUE THREAD

**Issue by InsanityComplx** [chaosvolt/MST_Extra_Mod#21]
I am getting an error that I don't exactly understand.
![Capture](https://user-images.githubusercontent.com/49550701/107153687-78277600-6934-11eb-9eab-12214c0d31d6.PNG)

**Comment by InsanityComplx** [comment]
It also does this with several other portions of the overrides it seems.

**Comment by chaosvolt** [comment]
Error should be skippable, I'll look into it and see if there's a sane cause or not.

**Comment by chaosvolt** [comment]
Ah, looks like there's a new syntax for harvesting, weird. Will fix in a bit.
