### ISSUE TITLE
Atlatal issues

### ISSUE THREAD

**Issue by InsanityComplx** [chaosvolt/MST_Extra_Mod#23]
Hello again!
Currently I am running across a few issues regarding the JSON of the Atlatal. Although I can just simply remove the Recipe and the offending JSON that causes it to show these errors, I feel I should make something official instead of just doing my ghetto fix for it.
This is the first error I get when the Mod is loading into the world;
![Atlatal 1](https://user-images.githubusercontent.com/49550701/125137622-acb18080-e0d2-11eb-9bfc-b97b05e6a65b.PNG)
And then when I try to look at the Atlatal in the crafting menu I get the Error;
![Atlatal 2](https://user-images.githubusercontent.com/49550701/125137719-dff40f80-e0d2-11eb-9cda-045576d65648.PNG)

I just wanted to let you know that I was getting these errors, because I was unsure if anyone else had been experiencing it.

**Comment by chaosvolt** [comment]
I think I see the problem. Somehow accidentally lost the pocket_data for the atlatl in the DDA version, right?

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/MST_Extra_Mod/commit/1853ed7d6c5feb3be87364d2360530fbd2e070b9 should hopefully fix it.

**Comment by InsanityComplx** [comment]
Oh awesome, I didn't know if it was an issue on the mods end or on the games end. Thanks for passing that merge on to me.
