### ISSUE TITLE
Field name issues.

### ISSUE THREAD

**Issue by InsanityComplx** [chaosvolt/MST_Extra_Mod#24]
I've been getting a numerous amount of field errors for various pieces of equipment from your mod; mostly about the encumbrance, covers, and coverage values. 
Most are occurring within the Obsolete, Items/Armor, Containers, and Items/tool_armor.

Here is an Example, but most of the errors look the same.
![yeet1](https://user-images.githubusercontent.com/49550701/126073724-7bf4532b-e6ae-498e-abf5-6064c72fbaa5.PNG)

**Comment by chaosvolt** [comment]
It's a 0.F Experimental change to have armor JSON is formatted. I need to set aside a 0.F Stable release of this mod then update them. I've done that for most of my other mods so far, just things are slow going due to being busy a lot these past couple days.

**Comment by InsanityComplx** [comment]
Ah I understand, not a problem, I have a backup version that works with the current state of the mod. I just wanted to make you aware of it if you didn't know.

I assume it'll show when you get it updated and working yeah?

**Comment by chaosvolt** [comment]
When I commit the changes to fix this I'll list it as closing this issue in the comments, yeah. Should be able to tackle it later today.

**Comment by InsanityComplx** [comment]
Thanks much my man, I'll keep an eye out.
