### ISSUE TITLE
Getting some field name errors

### ISSUE THREAD

**Issue by calrissian-tendra** [chaosvolt/MST_Extra_Mod#26]
DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/obsolete.json:205:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 2,
    "flags": [ "BELTED", "WATER_FRIENDLY" ],
    "armor":
            ^
             [ { "encumbrance": 12, "coverage": 30, "covers": [ "torso" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:16:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 1,
    "flags": [ "OVERSIZE" ],
    "armor":
            ^
             [ { "encumbrance": 5, "coverage": 50, "covers": [ "arm_l", "arm_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:32:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 1,
    "flags": [ "OVERSIZE" ],
    "armor":
            ^
             [ { "encumbrance": 5, "coverage": 50, "covers": [ "arm_l", "arm_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:48:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 1,
    "flags": [ "OVERSIZE" ],
    "armor":
            ^
             [ { "encumbrance": 5, "coverage": 50, "covers": [ "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:64:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 1,
    "flags": [ "OVERSIZE" ],
    "armor":
            ^
             [ { "encumbrance": 5, "coverage": 50, "covers": [ "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:84:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 1,
    "flags": [ "OVERSIZE", "OUTER", "ALLOWS_NATURAL_ATTACKS" ],
    "armor":
            ^
             [ { "encumbrance": 10, "coverage": 85, "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:101:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 3,
    "environmental_protection": 1,
    "armor":
            ^
             [ { "encumbrance": 30, "coverage": 85, "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:119:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 3,
    "environmental_protection": 1,
    "armor":
            ^
             [ { "encumbrance": 40, "coverage": 85, "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:138:13: Invalid or misplaced field name "armor" in JSON data

    "material_thickness": 4,
    "environmental_protection": 1,
    "armor":
            ^
             [ { "encumbrance": 50, "coverage": 85, "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:149:13: Invalid or misplaced field name "armor" in JSON data

    "volume": "1 L",
    "pocket_data": [ { "ammo_restriction": { "atlatl": 10 }, "moves": 30 } ],
    "armor":
            ^
             [ { "encumbrance": 5, "coverage": 15, "covers": [ "leg_l", "leg_r" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/armor.json:160:13: Invalid or misplaced field name "armor" in JSON data

    "volume": "1 L",
    "pocket_data": [ { "ammo_restriction": { "atlatl": 10 }, "moves": 30 } ],
    "armor":
            ^
             [ { "encumbrance": 15, "coverage": 15, "covers": [ "leg_l", "leg_r" ] } ]
  }
]

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/containers.json:28:15: Invalid or misplaced field name "armor" in JSON data

      "sided": true,
      "material_thickness": 1,
      "armor":
              ^
               [ { "encumbrance": 4, "coverage": 10, "covers": [ "leg_l", "leg_r" ] } ]
    },
    "flags": [ "WAIST" ]

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/tool_armor.json:35:13: Invalid or misplaced field name "armor" in JSON data

    "flags": [ "WAIST" ],
    "material_thickness": 2,
    "armor":
            ^
             [ { "encumbrance": 10, "coverage": 10, "covers": [ "torso" ] } ]
  },
  {

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/MST_Extra/items/tool_armor.json:61:13: Invalid or misplaced field name "armor" in JSON data

    "use_action": "GASMASK",
    "flags": [ "OUTER", "HELMET_COMPAT" ],
    "armor":
            ^
             [ { "encumbrance": 20, "coverage": 100, "covers": [ "head", "mouth", "eyes" ] } ]
  }
]

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/json.cpp
 LINE     : 122
 VERSION  : 0.F-2

**Comment by chaosvolt** [comment]
You're using current DDA Experimental version of MST Extra with 0.F Stable DDA.

Use the correct version: https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.F
