### ISSUE TITLE
Hobo stove warning (0.F-3)

### ISSUE THREAD

**Issue by Outcognito** [chaosvolt/MST_Extra_Mod#32]
I'm using 0.F release version
![image](https://user-images.githubusercontent.com/31615562/167301186-6b1f05ae-75de-4770-b462-41104587cd3f.png)
[debug.log](https://github.com/chaosvolt/MST_Extra_Mod/files/8647160/debug.log)

**Comment by chaosvolt** [comment]
There we go, this should fix it: https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.F-3
