### ISSUE TITLE
latest version cdda doesnt launch with latest version mst

### ISSUE THREAD

**Issue by alp7292** [chaosvolt/MST_Extra_Mod#43]
![Ekran Görüntüsü (189)](https://github.com/chaosvolt/MST_Extra_Mod/assets/82234624/f3deb8f5-b331-4976-b455-86e1ae906f9b)
![Ekran Görüntüsü (188)](https://github.com/chaosvolt/MST_Extra_Mod/assets/82234624/53227caf-11df-4ea0-a59d-6cbfaba5c6a5)

**Comment by chaosvolt** [comment]
Oh right, almost forgot about that.

**Comment by alp7292** [comment]
thanks for quick response and your hardwork. this mod is awesome

**Comment by chaosvolt** [comment]
No worries, just happened to be able to check online while getting ready to head out in a bit and spotted this.

This should fix it, but let me know if anything else comes up.
