### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by GlordXd** [chaosvolt/MST_Extra_Mod#44]
So um,dumb people like me dont know how to download files from repositories,can you please make a release with latest version of MST mod for DDA? Thanks in advance

Edit: though dark magic I've managed to download it,awesome mod btw,even though changes are somewhat little, they're very nice, definitely starring it

**Comment by chaosvolt** [comment]
I might need to set aside a release for 0.G stable, I forgot whether or not I already did, but the master branch is where you get current versions for latest experimental DDA and BN.
