### ISSUE TITLE
Hey there, I've got a bug report,i guess

### ISSUE THREAD

**Issue by GlordXd** [chaosvolt/MST_Extra_Mod#46]
So, there's a few errors I've been encountering for some time, the info is in the screenshots

![Screenshot_20230711_212315.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/e7d8bcfd-6150-4dbf-bb20-28abac943308)

![Screenshot_20230711_212351.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/1828b1c9-8993-42e5-9dcd-6924572fb1dd)

![Screenshot_20230711_212156.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/14ea0766-3c2e-4c8e-a77b-e3ae7c881f36)

![Screenshot_20230711_212346.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/967b06b3-0583-4a73-8969-87856841cbd7)

![Screenshot_20230711_212333.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/1b4c8fdb-7079-41ee-99be-946cf933dd17)

![Screenshot_20230711_212340.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/9c2fc16d-0b44-4a1a-aa7e-5e4ba94ad771)

![Screenshot_20230711_212304.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/d82aedca-20f6-4a09-b14e-13b57a422d5d)

![Screenshot_20230711_212257.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/98654914-c421-4e99-8a3e-af8340ebdcbf)

![Screenshot_20230711_212322.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/7d6e50cc-d607-4500-9b92-63d44f42c4d2)

(Im new to github,so let me know if there's something wrong with the screenshots)

Steps to reproduce the bug:
1) have these mods enabled
2) load a character into the world (doesn't matter if the character is new or not)
3) errors show up during the "vehicle parts" loading process

And one more thing... I'll provide additional info (what i can) if needed

**Comment by chaosvolt** [comment]
Sounds like your build of DDA is out of date, if you're using the latest experimental version of MST Extra from the main page.

**Comment by GlordXd** [comment]
> Sounds like your build of DDA is out of date, if you're using the latest experimental version of MST Extra from the main page.

Im currently using the 0.G (Gaiman) stable release of DDA

**Comment by chaosvolt** [comment]
Oh right, shit. I forgot to set aside a 0.G release for this mod.

**Comment by chaosvolt** [comment]
And set aside 0.G stable release: https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.G

**Comment by GlordXd** [comment]
> And set aside 0.G stable release: https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.G

Thanks
