### ISSUE TITLE
Another bug report (infinite dupe)

### ISSUE THREAD

**Issue by GlordXd** [chaosvolt/MST_Extra_Mod#47]
Hey there,like 10 minutes ago I've noticed a whole duping glitch (it can only duplicate woven straw beddings)

Steps to reproduce the dupe: 

1) craft one yourself and take it in hands
2) place it on the ground,and then remove it
3) the one you crafted is still in your hand,while the other one that you placed and removed is on the ground in the form of an item 

There are some screenshots:

![Screenshot_20230714_150328.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/290decfd-4c0c-4c3a-af04-b93d1968548b)

^This is the one I've crafted

![Screenshot_20230714_150340.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/7d2d9d01-9abf-4603-98ce-59fb30b06721)

^ thats the duplicate variant

![Screenshot_20230714_150856.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/d8d3161d-6b5d-4f6b-a816-04772a3caef3)

And finally me, sitting around all these beddings (the white hashtags)

The glitch is probably serious because its effectively infinite fire fuel bug

I'll provide additional info if needed

Technical info: 0.G (Gaiman) stable release of DDA

![Screenshot_20230711_212156.jpg](https://github.com/chaosvolt/MST_Extra_Mod/assets/138254662/b486d958-f6c6-427d-8da6-ffd351f52a59)

(The version of MST is the latest one)

**Comment by chaosvolt** [comment]
Ah, looks like it might be the lack of the `SINGLE_USE` flag.

**Comment by GlordXd** [comment]
> Ah, looks like it might be the lack of the `SINGLE_USE` flag

I'll be looking towards the bugfix (and potential errors,of course)

**Comment by chaosvolt** [comment]
Updated master branch and ported to 0.G release. https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.G-2

**Comment by GlordXd** [comment]
> Updated master branch and ported to 0.G release. https://github.com/chaosvolt/MST_Extra_Mod/releases/tag/0.G-2
> 
> Really weird that they need this flag for trap items but not furniture items, but that's DDA for you, inconsistent as always.

Thanks,human errors will always be there and the only really thing we can do is fix them.
