### ISSUE TITLE
CDDA: Posca generates an error. VitA does not exist.

### ISSUE THREAD

**Issue by ProjectMithril** [chaosvolt/MST_Extra_Mod#66]
When hovering over in recipes or when looking at the item Posca it generates an error. This is because it has VitA listed which does not exist in game.

This should probably be removed from the item.

**Comment by chaosvolt** [comment]
Hecc, will check on this in a bit, tomorrow if I don't get the chance tonight.

**Comment by chaosvolt** [comment]
There we go, sorry for the delay.
